version: '3.8'

services:
  tata-webhook:
    image: priyabratakhandual/tata-webhook:${IMAGE_TAG}
    container_name: tata-webhook
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./all_data:/app/all_data

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
